aya-y/freemarket_sample_37c

app/views/items/new.html.haml, spec/models/item_spec.rb
#what
商品出品機能の実装（remder一部変更）
#why
画像保存修正のため
=> Edit_render_"sell_img"

Gemfile, Gemfile.lock
=> add_gem_fog-aws

.gitignore, config/database.yml, config/initializers/carrierwave.rb
=> carrierwave_change

Gemfile
gem 'jquery-turbolinks’追加しました。
=> gem 'jquery-turbolinks'

app/assets/javascripts/calculator.js, app/views/items/_form.html.haml, app/views/items/edit.html.haml, app/views/items/new.html.haml
出品時の販売価格の計算機能を実装
本物：https://www.mercari.com/jp/sell/
機能を充実させるため
↓挙動
https://gyazo.com/2f0ddab56bbee4cb91b282086d3c0114
=> Add calculator

app/controllers/items_controller.rb, db/migrate/20181108043740_add_column_to_item.rb, db/schema.rb
Itemテーブルにstatusカラムの追加
購入状態表現のため
=> AddColumnToItem_status

db/migrate/20181109005430_change_status_to_item.rb, db/schema.rb
Itemテーブルのstatusカラムをinteger型に変更します。
enum使用のため
=> Change column status type

app/uploaders/image_uploader.rb, config/initializers/carrierwave.rb
Carrierwaveをコメントアウトしなければならない問題がこれで解決したかもしれません。
片平さんに感謝
=> comentout_problem_solving

app/assets/stylesheets/purchased.scss, app/controllers/users/sessions_controller.rb, app/views/devise/sessions/new.html.haml, app/views/users/_sidebar.html.haml, app/views/users/logout.html.haml, app/views/users/show.html.haml, config/routes.rb
=> login_and_logout

app/assets/stylesheets/_item_detail.scss, app/assets/stylesheets/config/colors.scss, app/views/items/show.html.haml, config/initializers/carrierwave.rb
=> Add item detail view

app/controllers/transaction_details_controller.rb, app/views/transaction_details/show.html.haml, app/views/users/completed.html.haml, app/views/users/in_progress.html.haml, app/views/users/purchase.html.haml, app/views/users/purchased.html.haml
・transaction-detailsの修正
┗中・小カテゴリのリンク先
┗商品確認後のリンク先を購入した取引に変更
不具合修正のため
=> Alter transaction detail

app/assets/stylesheets/_item_info.scss, app/controllers/items_controller.rb, app/views/items/_items.html.haml, app/views/items/index.html.haml, app/views/items/show.html.haml
トップページのピックアップカテゴリー修正
　・ピックアップアイテムのランダム表示
　・レディースカテゴリーの追加
アイテムの閲覧をスムーズにさせるため
=> Update top view

app/controllers/category_controller.rb, app/controllers/items_controller.rb
redirect先の変更
未ログイン時に購入、出品できないようにする。
=> Edit_item_controller

app/assets/javascripts/tab.js, app/assets/stylesheets/_item_info.scss, app/assets/stylesheets/users.scss, app/controllers/items_controller.rb, app/controllers/users_controller.rb, app/uploaders/image_uploader.rb, app/views/items/new.html.haml, app/views/users/_buying_item.html.haml, app/views/users/index.html.haml
マーイページ画面の修正（画像はS3の関係で現在表示されません）
　・ユーザーネーム、および出品数の表示
　・購入した商品のタブの切り替え、および購入商品の表示
機能を向上させるため
https://gyazo.com/d3585f0d42b56632d0c56de473f19e92
=> Update user page

app/controllers/items_controller.rb, app/controllers/transaction_details_controller.rb, app/controllers/users_controller.rb, app/uploaders/image_uploader.rb, app/views/items/_items.html.haml, app/views/items/shared/_item_three.html.haml, app/views/items/show.html.haml, app/views/users/show.html.haml, config/initializers/carrierwave.rb
itemのIndex周りの表示を修正した
購入後に応じて表示を変更するため
=> Adjust item index view

app/controllers/items_controller.rb, app/controllers/transaction_details_controller.rb, app/views/transaction_details/show.html.haml
商品詳細画面のルーティングの修正
ルーティングがおかしかったため
=> Fix_tramsaction_detail_controller

app/views/items/show.html.haml
itemのshow画面の修正
Bland未登録時に遷移できなかったため
=> Correct_item_show

app/controllers/blands_controller.rb, app/models/bland.rb, app/models/small_category.rb, app/views/blands/index.html.haml, app/views/items/new.html.haml, app/views/items/show.html.haml
ブランドと小カテゴリーにアソシエーションを作成
ブランドIndex画面でカテゴリー一覧を表示させるため
=> Cross associaton between bland and s category

app/views/small_category/show.html.haml
=> revise_small_category_name

app/controllers/blands_controller.rb, app/uploaders/image_uploader.rb, app/views/blands/index.html.haml, app/views/transaction_details/show.html.haml, config/initializers/carrierwave.rb
購入済み品にもsold_outのバッジの貼り付け
見栄えを良くするため
=> Add sold out badge

app/controllers/large_category_controller.rb, app/views/items/index.html.haml, app/views/items/show.html.haml, app/views/large_category/index.html.haml, app/views/transaction_details/show.html.haml, config/routes.rb
カテゴリールーティングの修正
トップページからのルーティングがエラーとなっていたため
=> Alter category link
